-- Reviews
CREATE TABLE reviews(
  review_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id int not null,
  rating int not null,
  review_date varchar(255) not null,
  summary varchar(255) not null,
  body text not null,
  recommend boolean,
  reported boolean,
  reviewer_name varchar(255) not null,
  reviewer_email varchar(255) not null,
  response text null,
  helpfulness varchar not null
);

COPY reviews(review_id, product_id, rating, review_date, summary, body, recommend, reported, reviewer_name, reviewer_email, response, helpfulness)
FROM '/Users/estevangonzalez/sdc/csv/reviews.csv'
DELIMITER ','
CSV HEADER;


-- Photos
CREATE TABLE photos(
  photo_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  review_id int,
  url_tag text not null,
  foreign key(review_id)
     references reviews(review_id)
        on delete cascade
);
COPY photos(photo_id, review_id, url_tag)
FROM '/Users/estevangonzalez/sdc/csv/reviews_photos.csv'
DELIMITER ','
CSV HEADER;

-- Characteristics
CREATE TABLE characteristics(
  char_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  review_id int,
  prod_name varchar(255) not null,
  foreign key(review_id)
    references reviews(review_id)
      on delete cascade
);
COPY characteristics(char_id, review_id, prod_name)
FROM '/Users/estevangonzalez/sdc/csv/characteristics.csv'
DELIMITER ','
CSV HEADER;

-- Meta Data
CREATE TABLE meta_data(
  data_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  char_id int,
  review_id int,
  data_value int not null,
  foreign key(char_id)
    references characteristics(char_id)
      on delete cascade,
  foreign key(review_id)
    references reviews(review_id)
      on delete cascade
);
COPY meta_data(data_id, char_id, review_id, data_value)
FROM '/Users/estevangonzalez/sdc/csv/characteristics.csv'
DELIMITER ','
CSV HEADER;