-- Reviews

CREATE TABLE reviews(
  review_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id int not null,
  rating int not null,
  review_date varchar(255) not null,
  summary varchar(255) not null,
  body text not null,
  recommend boolean not null default false,
  reported boolean not null default false,
  reviewer_name varchar(255) not null,
  reviewer_email varchar(255) not null,
  response text,
  helpfulness varchar not null default 0
);


COPY reviews(review_id, product_id, rating, review_date, summary, body, recommend, reported, reviewer_name, reviewer_email, response, helpfulness)
FROM '/home/unbuntu/sdc/reviews.csv'
DELIMITER ','
CSV HEADER;

CREATE INDEX review_index ON reviews USING btree (review_id);
CREATE INDEX prodId_review_index ON reviews USING btree (product_id);
SELECT setval('public.reviews_review_id_seq', (SELECT MAX(review_id) FROM reviews)+1);

-- Photos
CREATE TABLE photos(
  photo_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  review_id int,
  url_tag text not null,
  foreign key(review_id)
     references reviews(review_id)
        on delete cascade
);

COPY photos(photo_id, review_id, url_tag)
FROM '/home/unbuntu/sdc/reviews_photos.csv'
DELIMITER ','
CSV HEADER;

CREATE INDEX photo_review_index ON photos USING btree (review_id);
SELECT setval('public.photos_photo_id_seq', (SELECT MAX(photo_id) FROM photos)+1);

-- Characteristics
CREATE TABLE characteristics(
  char_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id int,
  prod_name varchar(255) not null
);


COPY characteristics(char_id, product_id, prod_name)
FROM '/home/unbuntu/sdc/characteristics.csv'
DELIMITER ','
CSV HEADER;

CREATE INDEX char_idx ON characteristics USING btree (product_id);
-- Meta Data
CREATE TABLE meta_data (
  data_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  char_id int,
  review_id int,
  data_value int not null,
  foreign key(char_id)
    references characteristics(char_id)
      on delete cascade
);

COPY meta_data(data_id, char_id, review_id, data_value)
FROM '/home/unbuntu/sdc/characteristic_reviews.csv'
DELIMITER ','
CSV HEADER;
CREATE INDEX data_idx ON meta_data USING btree (char_id);
SELECT setval('public.meta_data_data_id_seq', (SELECT MAX(data_id) FROM meta_data)+1);
